# Generated by Django 4.0.6 on 2022-07-27 00:52

from django.db import migrations


def populate_roles(apps, schemaeditor):
    roles = {
        "reader": "Does not work for the newspaper.",
        "journalist": "Works for the paper as a content creator.",
        "editor": "Reviews work of journalist."
    }
    Role = apps.get_model("accounts", "Role")
    for name, desc in roles.items():
        role_obj = Role(name=name, description=desc)
        role_obj.save()


def populate_departments(apps, schemaeditor):
    departments = {
        "front_page": "section tasked with writing headline article.",
        "sports": "sports section.",
        "society": "noone really cares about this section, not really.",

    }
    Department = apps.get_model("accounts", "Department")
    for name, desc in departments.items():
        dept_obj = Department(name=name, description=desc)
        dept_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
        migrations.RunPython(populate_roles),
    ]
